### PR TITLE
Fixing implementation after refactoring.

### PR DESCRIPTION
**Pull request by ajarzyn**

### CODE REVIEW

**Comment by ajarzyn** [comment]
Regarding #13 I did not test it well and was about to do it today, but you were able to merge this commit so quickly.

Few fixes that escaped me in version `1.0.3` please do not use that version.
`1.0.4` - is tested and should work just fine.

Please let me know if you encounter any troubles.

**Comment by ajarzyn** [comment]
There's still problem `onStop`

```
2023-10-08 14:10:53.458 Error: Fronius 4.1: Stop: Device 'Fronius 4.1 - F_PAC' Reference Count not correct, expected 1 found 2.
2023-10-08 14:10:53.458 Error: Fronius 4.1: Stop: Device 'Fronius 4.1 - F_FAC' Reference Count not correct, expected 1 found 2.
2023-10-08 14:10:53.458 Error: Fronius 4.1: Stop: Device 'Fronius 4.1 - F_IAC' Reference Count not correct, expected 1 found 2.
2023-10-08 14:10:53.458 Error: Fronius 4.1: Stop: Device 'Fronius 4.1 - F_IDC' Reference Count not correct, expected 1 found 2.
2023-10-08 14:10:53.458 Error: Fronius 4.1: Stop: Device 'Fronius 4.1 - F_UAC' Reference Count not correct, expected 1 found 2.
2023-10-08 14:10:53.458 Error: Fronius 4.1: Stop: Device 'Fronius 4.1 - F_UDC' Reference Count not correct, expected 1 found 2. 
```

But it's I do not find it harmful, and I think it's caused by the `Domoticz` engine itself:
https://github.com/domoticz/domoticz/issues/5379

**Comment by ajarzyn** [comment]
I'm finished here. Please merge.

**Comment by ajarzyn** [comment]
@ayasystems you closed it without merging.
It's a second PR with different commits.

Plugin is broken without this PR.

**Comment by ayasystems** [comment]
I'm sorry... is it ok now?

**Comment by ajarzyn** [comment]
yes it is now. Good job @ayasystems!

and sorry for that mess before, hope I did not caused to much trouble.

**Pull request merged**
